services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=starwars'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '${POSTGRES_PORT}:5432'

  redis:
    image: 'redis:7.4'
    ports:
      - '${REDIS_PORT}:6379'
